[package]
name = "sqldatetime"
version = "0.1.0"
authors = ["David Li <davidli2010@foxmail.com>"]
edition = "2018"
readme = "README.md"
license = "Apache-2.0"
description = "SQL date/time types written in Rust."
keywords = ["date", "time", "datetime", "timestamp", "SQL"]

[dependencies]
thiserror = "1.0.24"
stack-buf = "0.1.0"
